update libvirt-vnc cert & key when executing enroll certificates
oVirt/ovirt-engine pull request #138
Opened 2022-03-10 22:36 UTC by dangel101

2022-03-11 18:00 UTC, mwperina requested changes
Please provide a description in PR and commit what was changed and why and please also attach relevant bug.

2022-04-04 14:44 UTC, dangel101 commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/meta/main.yml
> -  - ovirt-host-deploy-facts
Actually I'm not sure why it was ever needed,
We don't use this dependency for the other certificates, and it works without it

2022-04-04 14:44 UTC, dangel101 commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/tasks/main.yml
> -      force: no
without it, it changes 'notBefore' to the current date

2022-04-05 08:20 UTC, ahadas approved these changes
infra know the details better, from virt point of view it makes sense to enroll the vnc certificate as well :)

2022-04-05 21:36 UTC, dangel101 commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/meta/main.yml
> -  - ovirt-host-deploy-facts
Actually I'm not sure why it was ever needed,
We don't use this dependency for the other certificates, and it works without it

2022-04-05 21:37 UTC, dangel101 commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/tasks/main.yml
> -      force: no
without it, it changes 'notBefore' to the current date

2022-04-05 21:59 UTC, mwperina commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/tasks/main.yml
> -      force: no
Ahh, now I get when I looked at ansible documentation, `force: no` means that files are copied only when they don't exist:

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/copy_module.html#parameter-force

2022-04-05 21:59 UTC, mwperina commented on packaging/ansible-runner-service-project/project/roles/ovirt-host-deploy-vnc-certificates/meta/main.yml
> -  - ovirt-host-deploy-facts
OK

2022-04-05 22:00 UTC, mwperina approved these changes
+1

2022-04-05 22:00 UTC, merged