engine: make host id mandatory for ProcessDownVmParameters
oVirt/ovirt-engine pull request #163
Opened 2022-03-16 10:13 UTC by ljelinkova

The ProcessDownVmCommand fails with NPE if the host id is null. This patch makes it mandatory for the caller to provide the host id and fails with IllegalArgumentException if the provided host id is null.

2022-03-16 12:02 UTC, liranr23 approved these changes

2022-03-16 16:40 UTC, ahadas requested changes

2022-03-18 09:02 UTC, ljelinkova commented on backend/manager/modules/common/src/main/java/org/ovirt/engine/core/common/action/ProcessDownVmParameters.java
> +            throw new IllegalArgumentException("The host id is required for processing down a vm");
ok, in case the host id provided is null, we just skip unpinning of the vm's cpus.

2022-03-20 14:27 UTC, ahadas approved these changes

2022-03-20 14:27 UTC, ahadas commented
/ost

2022-03-20 16:11 UTC, merged