use ansible-runner for playbook execution
oVirt/ovirt-engine pull request #187
Opened 2022-03-24 23:07 UTC by dangel101

replacing ansible-runner-service for playbook execution with ansible-runner

2022-03-25 08:23 UTC, michalskrivanek requested changes

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleClientFactory.java
> +//        client.setUUID(command.getUuid());
remove?

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleCommandConfig.java
> +//             If hostnames are empty we just don't pass any inventory file:
when does it happen?

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleConstants.java
> +//    public static final Path PROJECT_DIR = Paths.get(
please clean up comments here as well

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleExecutor.java
> +        log.info("****** inside runCommand****");
needed? please clean up debug logs

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java
> +        log.error("***inside run playbook***");
here as well. and i guess everywhere else;)

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/main/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClient.java
> +//                throw new AnsibleRunnerCallException(
so what do we do?

2022-03-25 08:23 UTC, michalskrivanek commented on backend/manager/modules/bll/src/test/java/org/ovirt/engine/core/common/utils/ansible/AnsibleRunnerHttpClientTest.java
> +//    private static Stream<Arguments> statusesForPlaybook() {
clean up please

2022-04-04 16:50 UTC, mwperina commented
https://github.com/oVirt/ovirt-engine/pull/214

2022-04-04 16:50 UTC, closed without merging