core: change messages during premature backup stop
oVirt/ovirt-engine pull request #208
Opened 2022-03-30 12:28 UTC by mkemel

When 'backup stop' command is performed before the backup is in 'READY'
state, confusing message 'finalizing failed' is shown in the event log
with ERROR.

Added a new backup phase 'PREMATURELY_STOPPED', and changed the event
log message to 'Backup $backupId for VM $vmName stopped prematurely'
with WARNING.

Also, changed the StopVmBackup command to succeed in this case, as the
command IMO does not fail if it does its purpose and stops the backup.
The StartVmBackup command though does fail.

Event log:
NORMAL: Backup fb926fba-2939-48ee-9acd-c7417254f5df for VM vm1 started (User: admin@internal-authz).
WARNING: Backup fb926fba-2939-48ee-9acd-c7417254f5df for VM vm1 stopped prematurely (User: admin@internal-authz).
ERROR: Backup fb926fba-2939-48ee-9acd-c7417254f5df for VM vm1 failed (User: admin@internal-authz).

2022-03-30 12:41 UTC, nirs requested changes
Adding new phase is bad. Stopping a backup should set a "stopped" flag, regardless of the the phase of the backup. The should check the stopped status and bail out cleanly regardless of the phase.

Also changing a delicate flow to improve a log message does not make sense. This is risky and require expensive testing and the value to users of the product is close to zero.

2022-03-30 18:14 UTC, barpavel commented
> 

Agree with Nir, no need to add a new phase.
This is just about improving `Events` log, and can be done totally inside `StopVmBackupCommand`.
As I see it, all you need is to pass between `executeCommand()` & `getAuditLogTypeValue()` some indication, that the failure is due to a premature cancel. And if so, return a newly defined  `AuditLogType` type declared as a warning with a proper phrasing explaining what happened.
Maybe you can find `getActionState()` useful or pass it by using `getParameters()` or add this flag as a new data of `StopVmBackupCommand` member (the latter IMHO might be not so elegant).

2022-03-31 06:28 UTC, mkemel commented
@barpavel @nirs Ack, got it, thanks

2022-04-07 06:27 UTC, ahadas commented on backend/manager/modules/dal/src/main/resources/bundles/AuditLogMessages.properties
> +VM_BACKUP_STOPPED_BEFORE_READY=Backup ${backupId} for VM ${VmName} stopped before reaching READY state (User: ${UserName}).
does it make a difference for users that the backup is stopped before reaching the 'ready' state? if not, let's not adding a different message for this case to reduce the translation effort

2022-04-18 06:04 UTC, closed without merging