el9: reload sockets during HE deploy
oVirt/ovirt-engine pull request #420
Opened 2022-06-07 14:14 UTC by michalskrivanek

2022-06-08 15:36 UTC, mwperina requested changes
Shouldn't all of this done only for `el_ver|int == 9`?

2022-06-08 15:40 UTC, michalskrivanek commented
> Shouldn't all of this done only for `el_ver|int == 9`?

it is, line 57

2022-06-09 07:08 UTC, mwperina approved these changes
+1

2022-06-09 07:23 UTC, tinez approved these changes

2022-06-09 07:36 UTC, merged