core: Uploading an image with an existing disk id
oVirt/ovirt-engine pull request #507
Opened 2022-06-30 06:45 UTC by ArtiomDivak

While uploading users can choose disk-id for thier uplaod and if
the disk-id was already existing the engine will make a new image
in lock state and fail the prosces. now it will check the disk-id before
creating and will fail if there is another disk-id with the same number.

Signed-off-by: Artiom Divak <adivak@redhat.com>

2022-06-30 09:24 UTC, ahadas commented
@ArtiomDivak I didn't look at the code changes but I've noticed that the commit here also doesn't point to the bug, please take a look at how it was done [here](https://github.com/oVirt/ovirt-engine/pull/495/commits/51f85f6efda9bb6a72b70429b2343224148ae057)

2022-07-04 14:28 UTC, dupondje commented on frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/AppErrors.properties
> +ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. One of the Template Disks already exists.
Its not a Template disk. But just a disk.

` ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. One of the disks already exists.`

2022-07-05 15:48 UTC, ahadas commented on frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/AppErrors.properties
> +ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. The following disks already exist.
and then let's list the disk aliases? :)

2022-07-06 06:51 UTC, ahadas reviewed
minor suggestion, besides that looks good

2022-07-06 06:51 UTC, ahadas commented on frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/AppErrors.properties
> +ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. The following disk already exist ${diskAlias}.
```suggestion
ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. The following disk already exist\:  ${diskAlias}. 
```

2022-07-11 11:02 UTC, ahadas approved these changes

2022-07-12 07:39 UTC, ljelinkova commented on frontend/webadmin/modules/frontend/src/main/resources/org/ovirt/engine/ui/frontend/AppErrors.properties
> +ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS=Cannot ${action} ${type}. The following disk already exist\: ${diskAlias}.
If the user selects and ID that already exists, the message would be more clear like this: The selected ID is already used by the following existing disk: ${diskAlias}.

2022-07-14 08:19 UTC, ahadas approved these changes

2022-07-14 08:27 UTC, bennyz approved these changes

2022-07-14 08:59 UTC, ljelinkova requested changes
I think you forgot to add `ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS` to `AppErrors.java`

2022-07-14 09:37 UTC, ahadas commented
> I think you forgot to add `ACTION_TYPE_FAILED_DISK_ALREADY_EXISTS` to `AppErrors.java`

indeed

2022-07-17 11:30 UTC, ahadas approved these changes

2022-07-17 13:19 UTC, ahadas commented
/ost

2022-07-17 14:52 UTC, merged