ui: Changed Incremental Backup from default true to false
oVirt/ovirt-engine pull request #613
Opened 2022-08-24 08:34 UTC by ArtiomDivak

When a user tried to upload anything the Incremental Backup tab
was by default checked from now on it will not be checked

Bug-Url: https://bugzilla.redhat.com/2120228
Signed-off-by: Artiom Divak <adivak@redhat.com>

2022-08-24 08:44 UTC, bennyz commented
I think we want to unset the checkbox only for ISO disks, not regular disks

2022-08-24 23:27 UTC, smelamud requested changes

2022-08-24 23:27 UTC, smelamud commented on frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/UploadImageModel.java
> +                diskModel.getIsIncrementalBackup().setEntity(false);
I think, `getDiskModel()` should be used here, like in all other places.

2022-08-25 06:22 UTC, ahadas commented on frontend/webadmin/modules/uicommonweb/src/main/java/org/ovirt/engine/ui/uicommonweb/models/storage/UploadImageModel.java
> +                diskModel.getIsIncrementalBackup().setIsChangeable(false);
please check if it changes to `changeable` again when picking another image that is not ISO (so you open the dialog, select an ISO so it gets disabled and then picking a different image that is not of type ISO)

2022-08-29 06:56 UTC, ahadas approved these changes

2022-08-29 07:02 UTC, ahadas commented
/ost

2022-08-29 07:30 UTC, ArtiomDivak commented
/ost

2022-08-29 07:33 UTC, ArtiomDivak commented
/ost

2022-08-29 07:57 UTC, ahadas commented
/ost

2022-08-29 08:07 UTC, ahadas commented
ost doesn't check it anyway and fails during the initialization part..

2022-08-29 08:07 UTC, merged

2022-08-29 08:12 UTC, michalskrivanek commented
> ost doesn't check it anyway and fails during the initialization part..

not good to ignore testing...