webadmin: add tabs to Options dialog
oVirt/ovirt-engine pull request #62
Opened 2022-02-09 12:09 UTC by rszwajko

Changes:
1. move existing user options to dedicated tabs to allow extending
   functionality in the future
2. create a General section with username and email (read only)

2022-02-09 12:33 UTC, rszwajko commented
### Before

![image](https://user-images.githubusercontent.com/64194103/153199498-4e3f27ad-0b68-4dd6-b59c-16d62dcbc67e.png)

### After

![image](https://user-images.githubusercontent.com/64194103/153200078-c7caa8cb-99b2-4bd5-ae52-80a035cd1acc.png)


![image](https://user-images.githubusercontent.com/64194103/153199886-5ee68d3f-21cb-4637-a5df-a596a431bd2d.png)


![image](https://user-images.githubusercontent.com/64194103/153199613-c5421d63-d408-4ad6-a195-52b942898f62.png)


![image](https://user-images.githubusercontent.com/64194103/153198917-f110f91d-a65e-4736-a93a-47e0bb630588.png)

2022-02-14 12:24 UTC, sgratch requested changes
The code looks good and the dialog looks great as well.
Few general comments:

- Dialog title and menu entry label should be changed to something like 'User or Account settings' or just  'Settings', instead of 'Edit options' and 'Options'. IMHO, worth using the same terminology like on the VM portal.
- Consider approaching this same dialog from the vertical navigation menu as well by adding another menu option e.g. Administration -> Settings.
The same dialog will be available from both menus but on the other hand, the same goes for events as well (events dialog and events drawer). 
This is an important dialog so it seems to me that adding that to the vertical navigation menu is better than leaving that under the upper masthead only. WDYT?
- General tab: the user's 'last name' option is missing
- Consider moving the 'User's Public Key' option to the general tab since there aren't any other console options for now so not sure that opening a dedicated 'Console' tab with one option is better. Once there will be more console options then we can always add more tabs.
- The same goes for future added session settings like 'default initial tab' and 'session timeout'. All those should be part of general section tab in my opinion.
Not sure about the 'Tables' tab.

- The issue mentioned here  https://bugzilla.redhat.com/show_bug.cgi?id=1950321 is reproduced again now.

2022-02-14 14:03 UTC, rszwajko commented
> * Dialog title and menu entry label should be changed to something like 'User or Account settings' or just  'Settings', instead of 'Edit options' and 'Options'. IMHO, worth using the same terminology like on the VM portal.
> 

+1

> * Consider approaching this same dialog from the vertical navigation menu as well by adding another menu option e.g. Administration -> Settings.
>   The same dialog will be available from both menus but on the other hand, the same goes for events as well (events dialog and events drawer).
>   This is an important dialog so it seems to me that adding that to the vertical navigation menu is better than leaving that under the upper masthead only. WDYT?
>

+1
 
> * General tab: the user's 'last name' option is missing
>

[The original design](https://marvelapp.com/prototype/6a95795/screen/62675607) included only User Name so Last Name was skipped.
We could add Last Name (and other fields) however IMHO this doesn't add much value and would duplicate functionality in Administration -> Users (actually even Administration -> Users -> [details] -> General is not displaying first/last name).

> * Consider moving the 'User's Public Key' option to the general tab since there aren't any other console options for now so not sure that opening a dedicated 'Console' tab with one option is better. Once there will be more console options then we can always add more tabs.
> 

Public key takes quite some place in the UI (although it's a single prop) - especially if we plan to expand the General section in the next PRs.

> * The same goes for future added session settings like 'default initial tab' and 'session timeout'. All those should be part of general section tab in my opinion.
>

+1

>   Not sure about the 'Tables' tab.
>

Depends on our plans (refresh timer? reset button?).
 
> * The issue mentioned here  https://bugzilla.redhat.com/show_bug.cgi?id=1950321 is reproduced again now.
>

Works for me. Please provide more information about scenario.

2022-02-15 11:40 UTC, rszwajko commented on frontend/webadmin/modules/gwt-common/src/main/resources/org/ovirt/engine/ui/common/CommonApplicationConstants.properties
> +emailUser=E-mail
This should be possible in Zanata.

2022-02-15 11:44 UTC, rszwajko commented
### Screenshots after renaming to Account Settings

![image](https://user-images.githubusercontent.com/64194103/154055533-69efed04-3e01-4f81-8614-0f38f94047f1.png)


![image](https://user-images.githubusercontent.com/64194103/154055439-a359ec9f-4a5b-4066-87b1-9a4782e71a9f.png)

![image](https://user-images.githubusercontent.com/64194103/154055354-d86bbabe-1443-48b6-971d-897d1667004b.png)

2022-02-16 19:14 UTC, sgratch commented
> > * General tab: the user's 'last name' option is missing
> 
> [The original design](https://marvelapp.com/prototype/6a95795/screen/62675607) included only User Name so Last Name was skipped. We could add Last Name (and other fields) however IMHO this doesn't add much value and would duplicate functionality in Administration -> Users (actually even Administration -> Users -> [details] -> General is not displaying first/last name).

Oops, what I meant here is that both first name + last name are missing (for users that have those set for him).

This was mentioned on our design (copied from the jira ticket: "Username (+ first name, last name if exists) - read only").
We are duplicating the email info as well, but we still display that here just to show the user his own general info. It is not displayed as part of the users-general tab, but it's displayed as part of the grid.  
I think this info is nice thing to display (if set), but if you think it's redundant then I'm totally ok with that. Just please update the ticket details so that QE won't search for that.

> 
> > * Consider moving the 'User's Public Key' option to the general tab since there aren't any other console options for now so not sure that opening a dedicated 'Console' tab with one option is better. Once there will be more console options then we can always add more tabs.
> 
> Public key takes quite some place in the UI (although it's a single prop) - especially if we plan to expand the General section in the next PRs.

Right, but on the other hand, having tabs with only one property each is also not that great design. And I anticipate users will ask for more console settings just because they see this empty console tab. If general tab includes only email and ssh key (in case first/last name is omitted) then won't there be a place for session timeout and initial tab?

> 
> > Not sure about the 'Tables' tab.
> 
> Depends on our plans (refresh timer? reset button?).

refresh times - not sure we'll have time for that
reset button - I'll check the other PR. I don't think reset should be at the same tab as other settings since this reset all tabs....

> 
> > * The issue mentioned here  https://bugzilla.redhat.com/show_bug.cgi?id=1950321 is reproduced again now.
> 
> Works for me. Please provide more information about scenario.

Check this screen recording. Only when clicking outside the text field, the ok button is enabled.

![Peek 2022-02-16 21-05](https://user-images.githubusercontent.com/18169498/154338510-3831b02c-99dc-4721-a73e-18a8c2d801f9.gif)

2022-02-16 19:18 UTC, sgratch reviewed
Please check the latest comment.

2022-02-17 15:49 UTC, rszwajko commented
@sgratch 
> please update the ticket details so that QE won't search for that.
>
Done

> If general tab includes only email and ssh key (in case first/last name is omitted) then won't there be a place for session timeout and initial tab?
>

Please check the new version with only 2 tabs. Note that since General tab has mixed content the header labels are needed. 

![image](https://user-images.githubusercontent.com/64194103/154517372-d85fb384-a3d3-4227-9ec8-a235bdcae982.png)

2022-02-17 15:54 UTC, sjd78 approved these changes
The code changes are straight-forward and LGTM

Design changes are reasonable:
 - Navigation points make sense to open the model
 - More tabs as the organization makes sense, but more so if there are say 3 or more items on each tab
 - The fewer tabs with sections on the tab page (as with the latest change) makes sense when there are not many items.

2022-02-17 23:42 UTC, sgratch approved these changes
LGTM

2022-02-18 00:47 UTC, merged